version: "2"
services:
  web-python:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8010:8010"
    links:
      - mysqldb
  mysqldb:
    #hostname: mysqlserver
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: maportofeup2014
      MYSQL_DATABASE: flask
